# Generated by Django 5.2.4 on 2025-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.CharField()),
                ("author", models.CharField()),
                ("post_on", models.DateField()),
                ("votes", models.BigIntegerField()),
            ],
        ),
    ]
