# Generated by Django 5.2.4 on 2025-07-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="quoate",
            new_name="quote",
        ),
    ]
